name: advanced-sample

services:
  advancedapi:
    container_name: advancedapi
    image: ${DOCKER_REGISTRY-}advancedapi
    build:
      context: .
      dockerfile: AdvancedApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      #- 'OTEL_EXPORTER_OTLP_ENDPOINT=http://todo-jaeger:4137'
      - 'OTEL_EXPORTER_OTLP_ENDPOINT=http://todo-seq:4137/ingest/otlp/v1/traces'
      - 'OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf'
    depends_on:
      - todo-db
      - todo-seq
      - todo-uptime
      #- todo-jaeger

  todo-db:
    container_name: todo-db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      - db:/var/lib/postgresql/data

  todo-db-admin:
    container_name: todo-db-admin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 15432:80
    depends_on:
      - todo-db

  todo-seq:
    container_name: todo-seq
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8090:80
      - 5341:5341

  # todo-jaeger:
  #   container_name: todo-jaeger
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - 4317:4317
  #     - 4318:4318
  #     - 16686:16686

  todo-uptime:
    container_name: todo-uptime
    image: louislam/uptime-kuma:latest
    volumes:
      - uptime:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

  todo-smtp:
    container_name: todo-smtp
    image: changemakerstudiosus/papercut-smtp:latest
    ports:
      - '25:25'
      - '8082:80'

volumes:
  db:
  uptime: